# Generated by Django 3.2.3 on 2025-11-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_ingredient_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
    ]
