# Generated by Django 4.2 on 2025-11-27 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
