# Generated by Django 4.2 on 2025-11-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
