FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

CMD ["gunicorn", "foodgram.wsgi:application", "--bind", "0.0.0.0:8000"]

ENTRYPOINT ["/app/entrypoint.sh"]

